version: '3.7'

services:
  punktura-backend-mysql:
    container_name: punktura-backend-mysql-dev
    ports:
      - '33063:3306'

  punktura-backend-php:
    container_name: punktura-backend-php-dev
    environment:
      APP_ENV: dev
      APP_VERSION: dev
      DATABASE_URL: mysql://root:@punktura-backend-mysql:3306/punktura-backend_dev
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@punktura-backend-rabbitmq-dev:5672/%2f/messages
      #SQS_MESSENGER_TRANSPORT_DSN: https://sqs.eu-central-1.amazonaws.com/016751366678/test
      SQS_TOPIC_NAME: tests
      SQS_ACCESS_KEY_ID: 016751366678
      SQS_ACCESS_KEY: AKIAQHZTVSILLR274DHI
      SQS_SECRET_ACCESS_KEY: 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
      SQS_REGION: eu-central-1

  punktura-backend-nginx:
    container_name: punktura-backend-nginx-dev
    ports:
      - '8083:80'

  punktura-backend-rabbitmq:
    container_name: punktura-backend-rabbitmq-dev
    ports:
      - '5672:5672'
      - '15672:15672'